name: Application Env Deploy

on:
  workflow_call:

env:
  PROJECT: DVSA Recalls

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-application:   
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: 
      name: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    
    - name: Update lambda function code
      run: echo "Lambda Updating"

  # TODO - ADD QA Workflow
