name: Application Release

on:
  workflow_dispatch:
    inputs:
      deploy_version:
        required: false
        type: number

env:
  PROJECT: DVSA Recalls

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:   
  dev-deployment:   
    # The type of runner that the job will run on
    uses: ./.github/workflows/app-env-deploy.yml
    with:
      env_deploy: dev

  int-deployment:   
    # The type of runner that the job will run on
    uses: ./.github/workflows/app-env-deploy.yml
    with:
      env_deploy: int
    needs: dev-deployment   

  preprod-deployment:   
    # The type of runner that the job will run on
    uses: ./.github/workflows/app-env-deploy.yml
    with:
      env_deploy: preprod
    needs: int-deployment   

  prod-deployment:   
    # The type of runner that the job will run on
    uses: ./.github/workflows/app-env-deploy.yml
    with:
      env_deploy: prod
    needs: preprod-deployment   

