name: Application Config

on:
  workflow_dispatch:
    inputs:
      env_config:
        description: JSON of app versions.
        required: false
        type: string  

env:
  PROJECT: DVSA Recalls
  APP_TEST: ${{ env.APP_REPO }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  application-config:   
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: 
      name: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    
    - name: echo config
      run: echo "${{ inputs.env_config }}"

    - name: List config from UI
      run: |
        jsonData='${{ inputs.env_config }}'
        for row in $(echo "${jsonData}" | jq -r '.[] | @base64'); do
          _jq() {
            echo "${row}" | base64 --decode | jq -r "${1}"
          }
          
          # OPTIONAL
          # Set each property of the row to a variable
          app=$(_jq '.app')
          value=$(_jq '.value')

          # Utilize your variables
          echo "$app = $value"
        done

    - name: List config from UI
      run: echo "$APP_TEST"