name: Application Release

on:
  workflow_dispatch:
    inputs:
      deploy_version:
        required: false
        type: number

env:
  PROJECT: DVSA Recalls

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:   
  dev-deployment:   
    # The type of runner that the job will run on
    runs-on: ubuntu-latest 
    uses: ./.github/workflows/app-env-deploy.yml
    environment: 
      name: dev