name: Application Env Deploy

on:
  workflow_call:
    inputs:
      env_vars:
        description: List of environment variables to set up, given in env=value format.
        required: false
        type: string  

env:
  PROJECT: DVSA Recalls

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-application:   
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.env_vars }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Set environment variables
      if: ${{ inputs.env_vars }}
      run: |
        for i in "${{ inputs.env_vars }}"
        do
          printf "%s\n" $i >> $GITHUB_ENV
        done
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    
    - name: Update lambda function code
      run: echo "Lambda Updating"

  # TODO - ADD QA Workflow
