name: CICD Flow

on:
  workflow_dispatch

env:
  Project: DVSA

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: github.ref == 'refs/heads/main'
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup
      run: echo "Setup ${{ github.event.repository.name }}"
     
    - name: Build
      run: echo "Building in ${{ github.event.repository.name }}"
    
    - name: Publish
      run: echo "Publish artifact from ${{ github.event.repository.name }}"

    - name: Deploy
      run: echo "Deploying project from ${{ github.event.repository.name }} for $DAY_OF_WEEK"
