name: CICD Flow

on:
  workflow_dispatch:
    inputs:
      deploy_version:
        required: false
        type: string

env:
  PROJECT: DVSA

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:   
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: 
      name: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    
    - name: Setup
      run: echo "Setup ${{ github.event.repository.name }}"
     
    - name: Build
      run: echo "Building in ${{ github.event.repository.name }}"
    
    - name: Publish
      run: echo "Publish artifact from ${{ github.event.repository.name }}"
    
    - name: Artifact
      run: echo "Upload artifact from ${{ github.event.repository.name }}" >> ./example.txt

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ./example.txt  

  dev-deployment:   
    # The type of runner that the job will run on
    runs-on: ubuntu-latest  
    environment: 
      name: dev
    needs: build  

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    
    - name: Deploy
      run: echo "Deploying project from ${{ github.event.repository.name }} for $PROJECT"

  manual-approve:
    needs: dev-deployment
    environment:
      name: approvers
    runs-on: ubuntu-latest
    steps:
    - name: manual approve
      run: echo "Manually approved"

  int-deployment:   
    # The type of runner that the job will run on
    runs-on: ubuntu-latest  
    environment: 
      name: int
    needs: dev-deployment  

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    
    - name: Deploy
      run: echo "Deploying project from ${{ github.event.repository.name }} for $PROJECT"